baseURL = "http://yuvalbloch.com/"
languageCode = "en-us"
title = "Acadmic Portfolio"
theme = "ananke"

[params]
  author = "yuval bloch"
  description = "Welcome to my academic portfolio!"
  custom_css = ["custom.css"]
  mainSections = ["posts"]
  ananke.show_recent_posts = true
  summaryLength = 10  # reduce to 25 words instead of 70



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true




[menu]
 [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 5


  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5

[params.ananke.social.follow]
  new_window_icon = true
  networks = ["github", "linkedin"]

[params.ananke.social.github]
  username = "your-github-username"
  profilelink = "https://github.com/yuvalbloch"
  rel = "me noopener"

[params.ananke.social.linkedin]
  username = "your-linkedin-username"
  profilelink = "https://linkedin.com/in/yuval-bloch191041192/"
  rel = "noopener"


