baseURL = "https://yuvalbloch.com/"
languageCode = "en-us"
title = "Complexity & Ecology Research"
theme = "ananke"
googleAnalytics = "G-G88CJRGNM1"
defaultContentLanguage = "en"  # Explicitly set the default language
enableRobotsTXT = true         # Best practice to enable this here

[params]
  author = "yuval bloch"
  description = "Exploring the dynamics of ecological systems and biological complexity to uncover the hidden patterns shaping our world."
  custom_css = ["custom.css"]
  mainSections = ["posts"]
  ananke.show_recent_posts = true
  omit_header_text = false
  summaryLength = 10  # reduce to 25 words instead of 70

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  # We will add translations for menu items later using i18n
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3


  [[menu.main]]
    name = "teaching"
    url = "/teaching/"
    weight = 5

[params.ananke.social.follow]
  new_window_icon = true
  networks = ["github", "linkedin"]

[params.ananke.social.github]
  username = "yuvalbloch"
  profilelink = "https://github.com/yuvalbloch"
  rel = "me noopener"

[params.ananke.social.linkedin]
  username = "yuval-bloch-191041192"
  profilelink = "https://www.linkedin.com/in/yuval-bloch-191041192/"
  rel = "noopener"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en" # Changed to 'en' for consistency
    weight = 1
    # You can add a title for this language, which might be different from the main title
    # title = "My English Site"

  [languages.he]
    languageName = "עברית"
    languageCode = "he"
    languageDirection = "rtl" # Crucial for Hebrew
    weight = 2
    title = "מחקר מורכבות ואקולוגיה" # Hebrew translation of the site title

# RobotsTXT and other output formats can be simplified by enabling them on a per-language basis if needed,
# but for now, they are fine as is.
[outputs]
  home = ["HTML", "RSS", "Sitemap"] # Removed "RobotsTXT" from here

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
